### ISSUE TITLE
[BUG] Some Titles Not Imported when using MAL Services Import

### ISSUE THREAD

**Issue by Zw012d** [Glagan/SyncDex#16]
**Describe the bug**
If u try to import titles from using MAL Services Import it will give error for some titles

**To Reproduce**
1. Go to MyAnimeList
2. Click on Import
3. It will give errors that some titles are not imported

**Expected behavior (optional)**
Not show any error

**Screenshots**
**Ex 1**
https://mangadex.org/manga/7645/flying-witch
https://myanimelist.net/manga/46258

![Screenshot 2020-12-29 172326](https://user-images.githubusercontent.com/76645315/103282266-3b926180-49fb-11eb-8986-f8906723ba31.png)
![Screenshot 2020-12-29 171854](https://user-images.githubusercontent.com/76645315/103282285-48af5080-49fb-11eb-978e-a14b59e32dc1.png)

**Ex 2**
https://mangadex.org/title/45253/junji-ito-a-study-from-the-abyss-of-horror
https://myanimelist.net/manga/119537
https://myanimelist.net/manga/44743 (two links because mal-sync link is different and incorrect)

![Screenshot 2020-12-29 172946](https://user-images.githubusercontent.com/76645315/103282398-a8a5f700-49fb-11eb-8d62-ffde7b119198.png)
![Screenshot 2020-12-29 173020](https://user-images.githubusercontent.com/76645315/103282400-aa6fba80-49fb-11eb-9a16-943ae462a30e.png)
![Screenshot 2020-12-29 173532](https://user-images.githubusercontent.com/76645315/103282687-8d87b700-49fc-11eb-9c55-a6aced227dd9.png)

**Ex 3**
https://mangadex.org/manga/4946/level-e
https://myanimelist.net/manga/1193

![Screenshot 2020-12-29 174911](https://user-images.githubusercontent.com/76645315/103283293-31259700-49fe-11eb-9467-9b318fa7ebbd.png)
![Screenshot 2020-12-29 174849](https://user-images.githubusercontent.com/76645315/103283294-32ef5a80-49fe-11eb-8816-9867e3378a3b.png)
![Screenshot 2020-12-29 174826](https://user-images.githubusercontent.com/76645315/103283298-371b7800-49fe-11eb-858d-4a1e620c5fda.png)

**Browser**
Chrome (0.1.7)

**Options and logs**
```
{"import":1609242028579,"lastSync":1609243011000,"logs":[{"d":1609242747562,"msg":"Obtained Dropbox token"},{"d":1609242748623,"msg":"Save already synced with Dropbox"},{"d":1609243008430,"msg":"No external lastSync or forced, uploading save."},{"d":1609243011635,"msg":"Uploaded Local Save to Dropbox"},{"d":1609243011638,"msg":"Synced your save with Dropbox"}],"options":{"acceptLowScore":false,"autoSync":true,"biggerHistory":true,"chapterStatus":true,"chaptersSaved":400,"checkOnStartup":true,"checkOnStartupCooldown":30,"checkOnStartupMainOnly":true,"colors":{"higherChapter":"transparent","highlights":["rgba(82, 190, 90, 0.6)","rgba(107, 177, 95, 0.6)","rgba(55, 168, 61, 0.6)"],"lowerChapter":"rgba(180, 102, 75, 0.5)","nextChapter":"rgba(104, 115, 251, 0.4)","openedChapter":"rgba(28, 135, 141, 0.4)"},"confirmChapter":false,"errorNotifications":true,"favoriteLanguage":"all","groupTitlesInLists":true,"hideHigher":true,"hideLast":false,"hideLower":true,"highlight":true,"iconsSilentAfterSync":true,"linkToServices":true,"mainService":"mal","mdUpdateSyncDex":true,"noReloadStatus":true,"notifications":true,"originalThumbnail":false,"overviewMainOnly":true,"progressInThumbnail":true,"saveOnlyHigher":true,"saveOnlyNext":false,"saveOpenedChapters":true,"separateLanguages":true,"services":["mal","mu","al","ku","ap"],"subVersion":7,"thumbnail":true,"thumbnailMaxHeight":80,"tokens":{"anilistToken":"set","kitsuToken":"set","kitsuUser":"set"},"updateMD":true,"updateOnlyInList":false,"useMochi":true,"version":0.1},"saveSync":{"expires":1609257147557,"refresh":"set","service":"Dropbox","token":"set"}}
```

**Additional context**
Ex 1 may be due to [58] as seen in screen shot , not sure about Ex 2 and 3

**Comment by Glagan** [comment]
I know about these issues, they are not related to **SyncDex**, but **mochi** (which is not open source).  
**MyAnimeList** (and **AnimePlanet** to some extent) had a bug at some point and some titles have missing informations, it's getting fixed but it just take some time since it's a long process and I can't do anything about that.

It will probably be fixed in less than a week, **but** that doesn't mean that all of these errors will disappear, since I can't create perfect connections without manual input, which I do not want to do since there is **a lot** to manage/keep track of.

There is no documentation about **mochi** but it's a "simple" (huge) database which create connections for each Services available in **SyncDex**, and there is around **422000** Titles (cumulated for all Services), and it's the only reason it's slow to update.  

In the future maybe manual input from user willing to help and manually fixing IDs for titles they found an error with might be implemented, but it's not a priority, the current system is "good enough" for most of the titles.
