### ISSUE TITLE
[REQUEST] add a option to the disable the new tab with the changelog on update.

### ISSUE THREAD

**Issue by M0UL** [Glagan/SyncDex#17]
**Is your feature request related to a problem? Please describe.**
it is really annoying that every time the extension update. it forces open a new tab  with the changelog. 

**Describe the solution you'd like**
add a option to turn it off.

**Comment by Glagan** [comment]
Well... sorry it bothers you, **SyncDex** was published a week ago and is still in "beta" that's why there is so many updates.  
My intent was that if you were using something but it was broken you could know if it was fixed.

I'll add an option, but you'll still have it happen once since it will be turned off by default.

**Comment by Glagan** [comment]
You need to enable the **Silent Update** option available since ``0.1.9`` and you won't be bothered for the next updates.
