### ISSUE TITLE
[REQUEST] should marking a title as "Dropped" change the completion date?

### ISSUE THREAD

**Issue by Jerrk** [Glagan/SyncDex#47]
I believe that changing a titles status to "dropped" is as significant as changing it to "completed", thats why i believe that changing the status to "dropped" should update the "completion date".

this is of course just my opinion and if you want to keep that field specifically for "Completed" only, i completely understand that.

**Comment by Glagan** [comment]
I don't think updating the *completion* date when you drop a title is relevant, since the goal of the field is in it's name, it's for when you *complete* a title, you could read 2 chapters and drop it, the completion date would lose it meaning.  
But you can use it how you want, it's also just my opinion.

I won't change it right now, maybe I'll make it possible in another way in the future or add an option, but there's currently a lot of things I'm already planning to do.
