### ISSUE TITLE
[BUG] volume only releases are not tracked

### ISSUE THREAD

**Issue by Jerrk** [Glagan/SyncDex#49]
**Describe the bug**
releases without a chapter doesnt get tracked

**To Reproduce**
view a title with a volume release with no chapter #

**Expected behavior (optional)**
should track volume releases

**Screenshots**
![](https://i.imgur.com/bCKZDWG.gif)

**Browser**
Firefox 88.0a1 (2021-03-11) (64-bit)

**Options and logs**
```
{"import":1615533500831,"lastSync":1615551994000,"logs":[{"d":1615551989896,"msg":"Forced, uploading save."},{"d":1615551993017,"msg":"Synced your save with Dropbox"}],"options":{"hideHigher":false,"hideLower":true,"hideLast":true,"highlight":true,"groupTitlesInLists":true,"thumbnail":true,"originalThumbnail":true,"progressInThumbnail":true,"thumbnailMaxHeight":80,"separateLanguages":true,"favoriteLanguage":"all","saveOpenedChapters":true,"chaptersSaved":100,"saveOnlyHigher":true,"saveOnlyNext":false,"confirmChapter":false,"updateOnlyInList":true,"iconsSilentAfterSync":false,"saveOnLastPage":true,"linkToServices":true,"overviewMainOnly":false,"mdUpdateSyncDex":true,"biggerHistory":true,"chapterStatus":false,"notifications":false,"errorNotifications":true,"errorDuration":1000,"infoDuration":4000,"successDuration":4000,"useMochi":true,"acceptLowScore":false,"updateMD":true,"updateMDProgress":true,"checkOnStartup":true,"checkOnStartupMainOnly":true,"checkOnStartupCooldown":10,"silentUpdate":false,"logLevel":0,"services":["al","mal","ku","mu"],"noReloadStatus":true,"tokens":{"kitsuToken":"set","kitsuUser":"set","anilistToken":"set"},"colors":{"highlights":["rgba(22, 65, 87, 0.8)","rgba(28, 103, 141, 0.8)","rgba(28, 135, 141, 0.8)"],"nextChapter":"rgba(199, 146, 2, 0.9)","higherChapter":"rgba(199, 146, 2, 0.1)","lowerChapter":"rgba(180, 102, 75, 0.4)","openedChapter":"rgba(28, 135, 141, 0.4)"},"version":0.3,"subVersion":0,"autoSync":true,"mainService":"al"},"saveSync":{"service":"Dropbox","token":"set","expires":1615563539096,"refresh":"set"}}
```

**Additional context**
i noticed the issue on this title
https://mangadex.org/title/31004/ijiranaide-nagatoro-san-comic-anthology

**Comment by Glagan** [comment]
Hum, this is a tricky one, I see the volume only as a secondary information and I'm not really using it when syncing, it's just "saved".  
Also, you can't always *use* it, **Anime-Planet** for example allow you to only store the volume OR the chapter and I choose the chapter, because in (almost) all situations you're using it over the volume.

I'm no sure how I would handle that, it would also mess with how I find the "next chapter" if I manually set a chapter (to 0 for example).  
Or I could do the same as I do for the volume and keep the previous chapter and update only the volume, but I think it would also have it's own problems on other pages.

I will try to think more about it, and if I end up doing something it might be the second idea.  
I might also do nothing, seems like these chapters should be "sub-chapters" of the main title and are volume endings (from the chapters name), but I understand that he created a new entry since it would pollute the main title with the long list of authors/artists.

**Comment by Glagan** [comment]
I managed to make something that seems to work, I'm still doing more tests before publishing, the only problem is when the uploader (or uploaders) are completly lost and can't keep the same convention for more than 2 chapters.  
So in the link you provided if your latest read is ``Vol. 2``, it won't find ``Vol. 3 Ch. 3`` as your next chapter since I need to keep a chapter and it will be either 0 or 1, that's not the previous for 3, and I have no way of knowing "where" does the current chapter progress come from (a release that had no chapter value).

This is a problem only if the ``Hide Higher`` option is enabled, since it will be hidden, and if ``Hide Higher`` is disabled it will just not be highlighted, still only when this particular chapter is your next one.
