### ISSUE TITLE
comments on 0.3.0

### ISSUE THREAD

**Issue by Jerrk** [Glagan/SyncDex#50]
the latest update added a couple of notifications that seem to be impossible to disable
![](https://i.imgur.com/QIEqYH7.gif)

i would like an option to disable these if possible 🙂 

It also doesn't seem that the blue notification has a progress bar and just instantly disappears, idk if that's intended but it's behavior is different from all other notifications AFAIK

i personally liked all the services in the top row as tabs for each service. 
the fixed width of the new service tabs doesn't look all that great, and at certain zoom levels will create a 2nd row where the last layout didn't (in my situation).

![](https://i.imgur.com/X1JYG5P.gif)

it also feels feels that the tabs move around too much when switching in-between the sources, i would suggest keeping the tabs static at the top and not transforming the region as much.

👍

**Comment by Glagan** [comment]
For the notifications, I was going to either remove them or add a parameter, the idea was there is a "Syncing" notification that you can close manually and it will go away when it finished syncing, but now that I think about it, it doesn't seems that useful.  
I added an option disabled by default to show them.

For the Overviews, the old design would also create a second row if the width was too small, and I don't think much about small devices (mostly phones) since for now I didn't test it at all for it, I will probably change it a bit when I do look to make it work for phones.  
I reduced the inactive Services width a bit.

For the animation, well, I like it so I don't know what to say, I lowered the duration a bit, and now there should be less height movement, when you change the displayed Service the old one directly goes to it's row instead of waiting for the animation.

I also made this design because code-wise it was really easy (especially more than the previous one) since it's just each independent overviews in a "list".  
I think you usually don't mess around with the Overviews too much, you only see how they move if you actually try to click them, and by default you only see the SyncDex and your main Service overview. Also, unless there is an icon, the content of the Overview is the same as the SyncDex one.

I might update it later if I have another idea that doesn't require too much change, but right now I will leave it like that.

**Comment by Jerrk** [comment]
heres a qucik comparison of what i mean:
![](https://i.imgur.com/3eaPrjR.gif)
in the old version the tabs do not move and its easier to navigate in-between them

![](https://i.imgur.com/WLSIx36.gif)
in 0.3.0 you have to search for the next location of the tab since the sizing is inconsistent

As you say, its not a big deal since you wouldnt be going back and forth between the services (for any reason im aware of). but personally i liked the previous version. 🙂

**Comment by Jerrk** [comment]
there also doesn't seem to be a way to disable the "progress updated" notification

**Comment by Glagan** [comment]
I added one in ``0.3.4``, it's enabled by default since it's the expected behavior when I update your list.
