### ISSUE TITLE
[QUESTION] I remember this was the best extension for syncing in the old days, do you intend to continue this idea?

### ISSUE THREAD

**Issue by MaxEhrhart** [Glagan/SyncDex#67]
Hi, how are you?

Just asking because I really loved how simple and easy it was to use your extension in the old mangadex and was wondering if you will release a new version of this extension. I know there MAL-Sync exists but it does not always work, and i think your extension was better.

Just asking because I remember this was a really good project.
Thanks

**Comment by Glagan** [comment]
Sorry for the late reply, SyncDex is abandoned, it died with MangaDex v5, but I was working on another "version" (tachikoma), but sadly I do these projects mostly for myself because I need them, and I'm not reading a lot lately.  
The project is not really abandoned, more like on hiatus, as other projects I do currently have higher interests for me, sorry.
